### ISSUE TITLE
included files in api not being found

### ISSUE THREAD

**Issue by spencerh-b** [Microsoft/AirSim#516]
I am trying to run an api based off of the most recent release, but when trying to build on ubuntu 14.04 all of the included cannot be found. I have had my api stored in the /include/api folder of the plugin, is there a different place to put the file now? Must I rewrite all of the file paths?

`__@__:~/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/api$ clang main.cpp
main.cpp:2:10: fatal error: 
      'vehicles/multirotor/api/MultirotorRpcLibClient.hpp' file not found
#include "vehicles/multirotor/api/MultirotorRpcLibClient.hpp"
         ^
1 error generated.
____@_____:~/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/api$ `

**Comment by sytelus** [comment]
Ubuntu 14.04 is not tested. Did you use the build instructions: https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md
