### ISSUE TITLE
CarState instance has no attribute 'collision'?

### ISSUE THREAD

**Issue by kecaiwu** [Microsoft/AirSim#708]
from AirSimClient import *
client = CarClient()
client.confirmConnection()
Waiting for connection:
client.enableApiControl(True)
car_controls = CarControls()
car_state = client.getCarState()

There are a issuse when perform the "car_state = client.getCarState()":

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "AirSimClient.py", line 556, in getCarState
    return CarState.from_msgpack(state_raw)
  File "AirSimClient.py", line 26, in from_msgpack
    obj.__dict__ = { k : (v if not isinstance(v, dict) else getattr(getattr(obj, k).__class__, "from_msgpack")(v)) for k, v in encoded.items()}
  File "AirSimClient.py", line 26, in <dictcomp>
    obj.__dict__ = { k : (v if not isinstance(v, dict) else getattr(getattr(obj, k).__class__, "from_msgpack")(v)) for k, v in encoded.items()}
AttributeError: CarState instance has no attribute 'collision'

Unreal 4.18 and LandscapeMountains is working OK in the Ubuntu16.04.

**Comment by sytelus** [comment]
I found the issue and it's now fixed in [this commit](https://github.com/Microsoft/AirSim/commit/b1ecc13f500a05d355dbe7aca65c200a3f4e0051). Please get latest. If you had done local changes to workaround this issue and then you might want to revert them first. 

Also, please note that there is slight change in APIs. Specifically, CarState structure now has [full kinematics](https://github.com/Microsoft/AirSim/blob/b1ecc13f500a05d355dbe7aca65c200a3f4e0051/PythonClient/AirSimClient.py#L159). This now allows you to get much more ground truth information about car's state in `kinematics_true` than just position and velocity.

Duplicate issues:

- https://github.com/Microsoft/AirSim/issues/708
- https://github.com/Microsoft/AirSim/issues/699
- https://github.com/Microsoft/AirSim/issues/711
