### PR TITLE
Use default sensors for default vehicle

### PR DESCRIPTION
**Pull request by rajat2004**
Fixes: #    

## About

This fixes a behavioural change I came across while testing #3719 

Use the settings -
```json
{
    "SettingsVersion": 1.2,
    "SimMode": "Multirotor"
}
```

and try using one of the sensor APIs such as `getImuData()`, etc. It throws an rpc error. Here's the output from `HelloDrone` -

```
Exception raised by the API, something went wrong.
rpclib: function 'getBarometerData' (called with 2 arg(s)) threw an exception. The exception is not derived from std::exception. No further information available.
```

This should work however, and it does work in 1.4.0, I think the change is due to [this](https://github.com/microsoft/AirSim/commit/006d4e2ac54f31e33ed595c6cdfbe2d5483027fd#diff-8ac7352e75eab96519f4de88358272d3b4de89e4b343ff35f228c5d7c3fc79ee). This error won't occur if a vehicle is present, even without any settings

It also adds the default sensors for vehicles created using the `simAddVehicle` API. Earlier, using any sensor APIs for these vehicle results in an error, and succeeds after this PR.

I tried using `make_unique` but that is giving some strange linker errors with the ROS wrapper somehow - `/home/testuser/AirSim/ros/devel/.private/airsim_ros_pkgs/lib/libairsim_settings_parser.so: undefined reference to `msr::airlib::AirSimSettings::kVehicleTypePhysXCar'` so have removed that for now

## How Has This Been Tested?

Above settings, and HelloDrone,

 - Works with 1.4.0
 - Doesn't work with 1.5.0, master
 - Works after this PR

`simAddVehicle` - Added `client.getImuData(vehicle_name=vehicle_name)` in `add_drone.py`, doesn't work earlier, works with this PR 

## Screenshots (if appropriate):

### CODE REVIEW

**Comment by jonyMarino** [comment]
Thanks, Rajat!
