### PR TITLE
[UE/Blueprint] Fix hidden previous declaration warnings

### PR DESCRIPTION
**Pull request by rajat2004**
```
1>  [1/4] Module.AirSim.cpp
1>D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(415): warning C4456: declaration of 'IndexBuffer' hides previous local declaration
1>  D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(406): note: see declaration of 'IndexBuffer'
1>D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(416): warning C4456: declaration of 'data' hides previous local declaration
1>  D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(396): note: see declaration of 'data'
1>D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(439): warning C4456: declaration of 'IndexBuffer' hides previous local declaration
1>  D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(406): note: see declaration of 'IndexBuffer'
1>D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(440): warning C4456: declaration of 'data' hides previous local declaration
1>  D:/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp(396): note: see declaration of 'data'
```

Tested till compilation only on Windows, API ([`simGetMeshPositionVertexBuffers()`](https://github.com/microsoft/AirSim/blob/master/docs/meshes.md#how-to-use))  tested to be working on Linux
Introduced by https://github.com/microsoft/AirSim/pull/2512
Related: https://github.com/microsoft/AirSim/issues/2523#issuecomment-609359504, #2545

### CODE REVIEW

**Comment by saihv** [comment]
I will give this a shot on Windows tomorrow. Any thoughts on why we seem to have a warnings vs. errors discrepancy?

**Comment by rajat2004** [comment]
> Any thoughts on why we seem to have a warnings vs. errors discrepancy?

Not sure, seems quite strange to me. One possibility could be the effect of different envs on the Plugins. Do any compiler flags specified for the env itself affect the plugin also? Don't have any idea about this, and that seems to be a possible reason as to the difference between Blocks & Landscape

**Comment by rajat2004** [comment]
@saihv I've tested that this fixes the compilation errors with LandscapeMountains on Windows
Closes #2548, #2545

**Comment by lfrusse** [comment]
Original Error message: **1>------ Build started: Project: TerraFormAirsim, Configuration: DebugGame_Editor x64 ------
1>Building TerraFormAirsimEditor...
1>Using Visual Studio 2017 14.16.27038 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 4 actions with 4 processes...
1>  [1/4] Module.AirSim.cpp
1>D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(415): error C4456: declaration of 'IndexBuffer' hides previous local declaration
1>  D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(406): note: see declaration of 'IndexBuffer'
1>D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(416): error C4456: declaration of 'data' hides previous local declaration
1>  D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(396): note: see declaration of 'data'
1>D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(439): error C4456: declaration of 'IndexBuffer' hides previous local declaration
1>  D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(406): note: see declaration of 'IndexBuffer'
1>D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(440): error C4456: declaration of 'data' hides previous local declaration
1>  D:/Unreal Projects/TerraFormAirSim/TerraFormAirsim/Plugins/AirSim/Source/AirBlueprintLib.cpp(396): note: see declaration of 'data'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "D:\Games\UE_4.24\Engine\Build\BatchFiles\Build.bat TerraFormAirsimEditor Win64 DebugGame -Project="D:\Unreal Projects\TerraFormAirSim\TerraFormAirsim\TerraFormAirsim.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "TerraFormAirsim.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
**

Then I try to implement the fix mentioned above and this is the error I get:

1>------ Build started: Project: TerraFormAirsim, Configuration: DebugGame_Editor x64 ------
1>Building TerraFormAirsimEditor...
1>Using Visual Studio 2017 14.16.27038 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 4 actions with 4 processes...
1>  [1/4] Module.AirSim.cpp
1>  [2/4] UE4Editor-AirSim-Win64-DebugGame.lib
1>     Creating library D:\Unreal Projects\TerraFormAirSim\TerraFormAirsim\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\DebugGame\AirSim\UE4Editor-AirSim-Win64-DebugGame.lib and object D:\Unreal Projects\TerraFormAirSim\TerraFormAirsim\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\DebugGame\AirSim\UE4Editor-AirSim-Win64-DebugGame.exp
1>  [3/4] UE4Editor-AirSim-Win64-DebugGame.dll
1>     Creating library D:\Unreal Projects\TerraFormAirSim\TerraFormAirsim\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\DebugGame\AirSim\UE4Editor-AirSim-Win64-DebugGame.suppressed.lib and object D:\Unreal Projects\TerraFormAirSim\TerraFormAirsim\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\DebugGame\AirSim\UE4Editor-AirSim-Win64-DebugGame.suppressed.exp
1>rpc.lib(client_error.obj) : error LNK2019: unresolved external symbol __CxxFrameHandler4 referenced in function "void * __cdecl std::_Allocate<16,struct std::_Default_allocate_traits,0>(unsigned __int64)" (??$_Allocate@$0BA@U_Default_allocate_traits@std@@$0A@@std@@YAPEAX_K@Z)
1>rpc.lib(server_session.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(this_handler.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(server.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(rpc_error.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(response.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(format.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(UdpClientPort.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(SocketInit.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(client.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(dispatcher.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkVehicleImpl.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(AdHocConnectionImpl.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(TcpClientPort.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(SerialPort.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(AdHocConnection.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(UdpSocketImpl.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkConnectionImpl.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkNodeImpl.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(WindowsFindSerialPorts.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkMessages.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkNode.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkVehicle.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(UdpSocket.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(Semaphore.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkMessageBase.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>MavLinkCom.lib(MavLinkConnection.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
1>rpc.lib(client_error.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>rpc.lib(server_session.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>rpc.lib(dispatcher.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>rpc.lib(server.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>rpc.lib(rpc_error.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>rpc.lib(format.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(SerialPort.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(UdpClientPort.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(SocketInit.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>rpc.lib(client.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(MavLinkNodeImpl.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(MavLinkVehicleImpl.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(AdHocConnectionImpl.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(TcpClientPort.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(MavLinkNode.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(AdHocConnection.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(UdpSocketImpl.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(MavLinkConnectionImpl.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(Semaphore.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(MavLinkMessageBase.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(WindowsFindSerialPorts.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>MavLinkCom.lib(MavLinkMessages.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>D:\Unreal Projects\TerraFormAirSim\TerraFormAirsim\Plugins\AirSim\Binaries\Win64\UE4Editor-AirSim-Win64-DebugGame.dll : fatal error LNK1120: 2 unresolved externals
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "D:\Games\UE_4.24\Engine\Build\BatchFiles\Build.bat TerraFormAirsimEditor Win64 DebugGame -Project="D:\Unreal Projects\TerraFormAirSim\TerraFormAirsim\TerraFormAirsim.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "TerraFormAirsim.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


Is there a fix for running AirSim with UE 4.24.x?

**Comment by rajat2004** [comment]
Hi,
You're using VS 2017, however latest AirSim requires 2019 version. Please see https://microsoft.github.io/AirSim/build_windows/ for details and try again
Thanks!

**Comment by lfrusse** [comment]
Even though i was using VS 2019 for some reason it was trying to use VS 2017 to compile. I uninstalled VS 2017 and it worked. Thanks!

**Comment by saihv** [comment]
I've tested it on 2019 as well, works.

**Comment by bys1123** [comment]
@lfrusse Looks like I need to uninstall VS2017 then.......

**Comment by bys1123** [comment]
@lfrusse I find the way, 
Open C:\Users\$user\AppData\Roaming\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml

Change to
```
<?xml version="1.0" encoding="utf-8" ?>
<Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
    <BuildConfiguration>        
    </BuildConfiguration>

    <VCProjectFileGenerator>
        <Version>VisualStudio2019</Version>
    </VCProjectFileGenerator>

    <WindowsPlatform>
        <Compiler>VisualStudio2019</Compiler>
    </WindowsPlatform>
</Configuration>
```

**Comment by madratman** [comment]
Ah you can also change this in the editor by
Editor Preferences -> General -> Source Code -> Source Code Editor
And select vs 2019.
I'm guessing that should modify the xml as well.

**Comment by madratman** [comment]
Also, I'm not sure how your comments relate to this PR, but hope that helps.
If this is relevant to another issue thread, please refer it or we can move the discussion there.

**Comment by johan606303** [comment]
> 
> 
> @lfrusse I find the way,
> Open C:\Users$user\AppData\Roaming\Unreal Engine\UnrealBuildTool\BuildConfiguration.xml
> 
> Change to
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
>     <BuildConfiguration>        
>     </BuildConfiguration>
> 
>     <VCProjectFileGenerator>
>         <Version>VisualStudio2019</Version>
>     </VCProjectFileGenerator>
> 
>     <WindowsPlatform>
>         <Compiler>VisualStudio2019</Compiler>
>     </WindowsPlatform>
> </Configuration>
> ```

I tried that. But even so, I still can't compile even MontainsLandscape yet.

I'm using VS2019.
UE4, 4.24.3.

**Comment by rajat2004** [comment]
@johan606303 Try with the latest master
Best to open a new issue with complete details of system configuration, steps to reproduce, error details
